# Generated by Django 5.2.10 on 2026-02-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_order_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=180, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(max_length=120, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='order',
            name='reference',
            field=models.CharField(blank=True, max_length=180, verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='order',
            name='whatsapp',
            field=models.CharField(max_length=30, verbose_name='WhatsApp'),
        ),
    ]
