# Generated by Django 5.2.10 on 2026-02-14 07:16

import django.db.models.deletion
import shop.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_price_orderitem_unit_price_order_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Sin pago'), ('pending_review', 'Comprobante en revisión'), ('paid', 'Pagado')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='receipt_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default=shop.models._new_order_code, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='', max_length=120, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/', verbose_name='Comprobante'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Nuevo'), ('confirmed', 'Confirmado'), ('preparing', 'Preparando'), ('on_the_way', 'En camino'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='whatsapp',
            field=models.CharField(default='', max_length=30, verbose_name='WhatsApp'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Casa', max_length=60, verbose_name='Etiqueta')),
                ('full_name', models.CharField(max_length=120, verbose_name='Nombre completo')),
                ('whatsapp', models.CharField(max_length=30, verbose_name='WhatsApp')),
                ('address', models.CharField(max_length=180, verbose_name='Dirección')),
                ('reference', models.CharField(blank=True, max_length=180, null=True, verbose_name='Referencia')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('is_default', models.BooleanField(default=False, verbose_name='Predeterminada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
